apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubeknit
spec:
  version: "{{ .TagName }}"
  platforms:
    - {{addURIAndSha "https://github.com/KubeHat/kubeknit/releases/download/{{ .TagName }}/bundle.tar.gz" .TagName | indent 6 }}
      bin: kubeknit-krew
      files:
        - from: ./kubeknit-krew
          to: .
        - from: LICENSE
          to: .
      selector:
        matchExpressions:
          - key: os
            operator: In
            values: ["darwin", "linux"]
  shortDescription: Merge, split, import or delete kubeconfig files
  homepage: https://github.com/KubeHat/kubeknit
  description: |+2

      kubeknit helps to merge, split, import or delete kubeconfig files

      This is a convenience wrapper around the `kubectl config view` command.

      Usage:
        $ kubectl kubeknit import --save new-cfg
        $ kubectl kubeknit delete --save ctx1
        $ kubectl kubeknit merge kubeconfig1 kubeconfig2 > merged
        $ kubectl kubeknit export ctx1 ctx2 -k k8s.yaml,k3s.yaml > extracted

      More on https://github.com/KubeHat/kubeknit#usage
